CREATE TABLE departamentos(
  id INTEGER PRIMARY KEY NOT NULL,
  nome VARCHAR(64) NOT NULL CONSTRAINT "UPPER_NOME" CHECK (nome = UPPER(nome)),
  faculdades_id INTEGER DEFAULT NULL REFERENCES faculdades(id) ON DELETE SET DEFAULT
);