CREATE TABLE departamentos(
  id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  nome VARCHAR(64) NOT NULL CONSTRAINT "UPPER_NOME" CHECK (nome = UPPER(nome)),
  faculdades_id INTEGER DEFAULT NULL REFERENCES faculdades ON DELETE SET DEFAULT
);