CREATE TABLE listas (
  id    INTEGER PRIMARY KEY NOT NULL,
  nome  VARCHAR(128)        NOT NULL,
  votos INTEGER             NOT NULL DEFAULT 0,
  tipo  VARCHAR(10) NOT NULL DEFAULT 'STUDENT' CONSTRAINT "lists_valid_type"
  CHECK ( tipo IN ('STUDENT', 'TEACHER', 'JANITOR')),
  eleicao INTEGER DEFAULT NULL -- TODO REFERENCES eleicoes(id) ON DELETE CASCADE
)